name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Ajusta la versión según tus necesidades

    - name: Restore dependencies
      run: dotnet restore src/

    - name: Build
      run: dotnet build src/ --configuration Release
